mel_augmentation:
  time_masking:
    enabled: true
    max_length: 12
    max_masks: 1
    p: 0.25

  freq_masking:
    enabled: true
    max_length: 8
    max_masks: 1
    p: 0.25

  normalization:
    enabled: true
    eps: 1e-05
    standard: true
    minmax: false

mixup:
  enabled: true
  p: 0.5
  alpha: 0.4